#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: ./sync <node_ip>"
  exit 1
fi

rsync -avz --exclude disable_unity/ /home/blue/Index_Coding_Testbed_V2/ blue@"$1":/home/blue/Index_Coding_Testbed_V2

